# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Per aspera ad astra"
description: > # this means to ignore newlines until "email:"
  Load to Technical Management

email: to_hongju@pm.me
#blog logo
logo: "/assets/images/hj_logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'YI Hong-ju'
author: 'YI Hong-ju'
author_image: "/assets/images/author.png" # Origin: author.jpg

paginate:	5

url: "https://yi-hongju.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@no-twitter'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://yi-hongju.github.io
    desc: Watch my GitHub Page
    share_url: https://yi-hongju.github.io
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://yi-hongju.github.io
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/YI-Hongju
    desc:	Fork me on GitHub
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://yi-hongju.github.io
    desc:	Fork me on GitHub
#    share_url:
#    share_title:
#    share_link:
